<a href="https://colab.research.google.com/github/yoon0416/python/blob/main/%EC%8B%A4%EC%8A%B51010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data = [1,2,3,4]
result = []
for i in data:
    result.append(i*10)
print(result)

[10, 20, 30, 40]


리스트 안에 있는 값 10 곱하기

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

arr10 = arr*10

print(arr10)

[10 20 30 40]


넘파이 사용

# **판다스**
-데이터 프레임 자료구조를 제공하여 분석을 돕는 파이썬의 핵심 패키지

# **시리즈: 인덱스 값이 한 쌍을 이루는 판다스의 1차원 자료구조 객체**
- 파이썬의 리스트 값만 있고 인덱스가 0부터 자동 생성된다
- 판다스의 시리즈는 사용자가 직접 인덱스를 정할 수 있음(기본은 자동 생성)

In [ ]:
from pandas import Series, DataFrame

data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [ ]:
from pandas import Series, DataFrame

data = [100, 200, 300]
index = ["월","화","수"]
s = Series(data,index)
print(s)

월    100
화    200
수    300
dtype: int64


# **데이터프레임: 판다스의 기본 구조인 자료구조 객체**

1.   시리즈 여러 개를 묶어서 데이터 프레임을 만들어 2차원 배열과 비슷
2.   행 인덱스, 열 이름(또는 열 인덱스), 값으로 구성

- 행(인덱스): 가로줄만 행으로 구분하는 고유한 인덱스
- 열(칼럼, 열 인덱스): 세로줄만 열을 열이름으로 구분
- 값(데이터): 행과 열이 교차하는 곳에 지정되는 데이터

In [ ]:
from pandas import DataFrame

data = [
    [157000,39.88,4.38],
    [51300,8.52,1.45],
    [68000,10.03,0.87],
    [140000,228368,2.16]
    ]
index = ['Naver','삼성전자','LG전자','카카오']
columns = ['종가','PER','PBR']
df = DataFrame(data = data,index = index,columns = columns)
print(df)

           종가        PER   PBR
Naver  157000      39.88  4.38
삼성전자    51300       8.52  1.45
LG전자    68000      10.03  0.87
카카오    140000  228368.00  2.16


In [ ]:
import numpy as np

list1 = [1,2,3,4]
a = np.array(list1)
print('a.shape: ',a.shape)
print('a[0]',a[0])

a.shape:  (4,)
a[0] 1


- flatten(): 1차원 배열로 변경
- resize(i,j): 배열의 모양을 i x j로 변경
- transpose(): 열과 행을 교차

In [ ]:
import numpy as np

a = np.array([[0,1,2],[3,4,5]])
print('a\n',a)

b= a.transpose()
print('b\n',b)

c = a.T
print('c\n',c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


# **마스킹**

- 논리값 인덱싱(Boolean indexing) 또는 마스킹(masking) 조건에 맞는 값을 출력
- 데이터 양이 많을 때 반복문으로 조건을 검사하지 않고도 원하는 데이터 찾을 수 있음

# **유니버설 함수와 브로드캐스팅**
- 유니버설 함수: 덧셈, 뺄셈, 곱셈, 거듭제곱처럼 배열 요소끼리의 기본연산을 수행
- 반복문을 활용하는 것보다 월등히 빠르고 효율적인 연산

# **배열복사**
- 얕은복사: 등호를 이용하는 복제, 원본배열 수정하면 복사본이 함께 바뀜 그 반대도 마찬가지
- 깊은복사: copy함수를 사용 원본에 영향 x

In [ ]:
import numpy as np
a = np.arange(6)
b = a #얕은 복사

print(a)
print(b is a)

b[0] = 10
print(a)

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


In [ ]:
a = np.arange(6)
c = a.copy() #깊은 복사

c[0] = 20
print('A: ',a)
print('C: ',c)

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


# **배열정렬**
- sort() 함수 사용

# **판다스 활용**

In [ ]:
import pandas as pd

a= pd.Series([1,2,3,4]) #인덱스를 지정하지 않았으므로 기본 인덱스로 숫자 0,1,2,3이 지정
print(a)
b = pd.Series([1,2,3],index = ['a','b','c']) #값 1,2,3,에 인덱스로 문자열 a,b,c를 지정
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64


In [ ]:
list2 = list([['한빛','남자','20','180'], #씨발
             ['한결','남자','21','177'],
             ['한라','여자','20','160']])
col_names = ['이름','성별','나이','키']
pd.DataFrame(list2, columns = col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160


In [ ]:
import pandas as pd

list1 = [['허준호','남자','30','183'],
               ['이가원','여자','24','162'],
               ['배규민','남자','23','179'],
               ['고고림','남자','21','182'],
               ['이새봄','여자','28','160'],
               ['이보람','여자','26','163'],
               ['이루리','여자','24','157'],
               ['오다현','여자','24','172']]
col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns=col_names)
print(df)


    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172


In [ ]:
df.head(3)

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

In [ ]:
df.tail()

이름  성별  나이    키
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

- head()함수: 데이터 프레임의 처음 n개의 행
- tail()함수: 데이터 프레임의 마지막 n개의 행
- 기본값 처음 5행

In [ ]:
df.sort_index(axis=0).head()

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

- 행 정렬: 인덱스나 특정열의 값을 기준으로 행을 정렬할 수 있다
- 기본 정렬 방향은 오름차순이며 내림차순 정렬은 ascending 인자를 false로 지정하면 됨

In [ ]:
df.sort_values(by='나이',ascending=False).head()

이름  성별  나이    키
0  허준호  남자  30  183
4  이새봄  여자  28  160
5  이보람  여자  26  163
1  이가원  여자  24  162
6  이루리  여자  24  157

- sort_values(): 특정 열을 기준으로 정렬 할 수 있음

# **데이터 조회**
- 데이터를 열이나 조건식 기준으로 조회할 수 있음
데이터프레임[조건식]
데이터프레임[[조건식]]

In [ ]:
df[['이름','키']].head()

이름    키
0  허준호  183
1  이가원  162
2  배규민  179
3  고고림  182
4  이새봄  160

iloc함수: 행인덱스와 열 이름을 함께 입력할땐 행인덱스를 먼저쓰고 열 이름을 씀

In [ ]:
df.iloc[1:4,0:3] #두번째 행부터 4번째 행의 첫번째 열부터 새번째 열 조회

이름  성별  나이
1  이가원  여자  24
2  배규민  남자  23
3  고고림  남자  21

In [ ]:
import pandas as pd

list2 = [['허준호','남자',30,183],
               ['이가원','여자',24,162],
               ['배규민','남자',23,179],
               ['고고림','남자',21,182],
               ['이새봄','여자',28,160],
               ['이보람','여자',26,163],
               ['이루리','여자',24,157],
               ['오다현','여자',24,172]]
col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list2, columns=col_names)
print(df)


    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172


In [ ]:
df[df['키'] > 180].head() #''로 인하여 자료형이 문자열이기 때문에 숫자 데이터는 비교조건으로 할 때 자료형을 숫자형으로 바꿔줘야함 안그럼 오류 ㅈㄴ 뜸 ㅅㄱ

이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [ ]:
df[df['나이'].isin([21,23])] #조건식에 isin()함수, and기호, or기호, str.contains()함수를 사용하여 더 복잡한 조건으로 조회할 수 도 있음

이름  성별  나이    키
2  배규민  남자  23  179
3  고고림  남자  21  182

In [ ]:
df[(df['성별'] == '여자') & (df['키']>160)]

이름  성별  나이    키
1  이가원  여자  24  162
5  이보람  여자  26  163
7  오다현  여자  24  172

In [ ]:
df[(df['나이'] >= 28) | (df['성별'] == '남자')]

이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [ ]:
df[df['이름'].str.contains('봄')]

이름  성별  나이    키
4  이새봄  여자  28  160

In [ ]:
df.loc[4,'키'] = df.loc[4,'키'] +5
df.loc[[4]]

이름  성별  나이    키
4  이새봄  여자  28  165

In [ ]:
df['보너스'] = df['나이']*10000
df.head(3)

이름  성별  나이    키     보너스
0  허준호  남자  30  183  300000
1  이가원  여자  24  162  240000
2  배규민  남자  23  179  230000